### ISSUE TITLE
Enable the access to the preferences dialog

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/spacelab-transmitter#27]
When the preferences button is clicked, the preferences dialog should appear on the screen.

**Comment by vitoria-b** [comment]
Coloquei também as funções referentes a clicar nos botões dentro do dialog e a _save_preferences e _load_default_preferences. Das constantes foi só adicionado a _DEFAULT_CALLSIGN, _DEFAULT_LOCATION e _DEFAULT_COUNTRY pra esse commit.

**Comment by mgm8** [comment]
> Coloquei também as funções referentes a clicar nos botões dentro do dialog e a _save_preferences e _load_default_preferences. Das constantes foi só adicionado a _DEFAULT_CALLSIGN, _DEFAULT_LOCATION e _DEFAULT_COUNTRY pra esse commit.

[No hablo chino!](https://youtu.be/HCIwXGq0zD0?t=25) :)

**Comment by mgm8** [comment]
The preferences dialog reapers once just after closing:

![preferences_bug](https://user-images.githubusercontent.com/5316364/166561859-b375b7b9-f1c9-49b5-ab4f-5dba3fc83fe2.gif)
