### ISSUE TITLE
Design a dialog to handle the "Broadcast Message" telecommand

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/spacelab-transmitter#91]
When the "Broadcast Message" telecommand is requested, a dialog with two text fields should appear:

1. The destination callsign
2. The message to broadcast

An "Send" and "Cancel" button should also be included. When the "Send" button is clicked, the telecommand is transmitted with the information presented in the text fields. When the "Cancel" button is clicked, the operation is aborted.

**Comment by vitoria-b** [comment]
The code and the UI interface has been updated with the dialog, but there's a bug when exiting the dialog, the bug is described in this issue which is the next step: https://github.com/spacelab-ufsc/spacelab-transmitter/issues/97
