### ISSUE TITLE
Add a label to the switch of the telecommands' buttons

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/spacelab-transmitter#98]
Now, it is not so clear what the telecommands' switch does or how to change sensibility of the telecommands' buttons. Adding a label describing the functionality of the switch button should improve the usability of the software.

**Comment by vitoria-b** [comment]
Could it be a markup so the text only appears when the mouse is on top of it?

**Comment by mgm8** [comment]
> Could it be a markup so the text only appears when the mouse is on top of it?

I think a label would be better, but a markup will also help to understand the purpose of this widget. Maybe we should use both.
